#define ADC_CHAN ADC_Channel_1
#define STDOUT_USART uart2
#define USE_USART_1
#define GPIO_USART1_TX_PORT GPIOA
#define GPIO_USART1_TX_PIN 9
#define GPIO_USART1_TX_AF 7
#define GPIO_USART1_RX_PORT GPIOA
#define GPIO_USART1_RX_PIN 10
#define GPIO_USART1_RX_AF 7
#define USE_USART_2
#define GPIO_USART2_TX_PORT GPIOA
#define GPIO_USART2_TX_PIN 2
#define GPIO_USART2_TX_AF 7
#define GPIO_USART2_RX_PORT GPIOA
#define GPIO_USART2_RX_PIN 3
#define GPIO_USART2_RX_AF 7
#define GPIO_LED1_PORT GPIOA
#define GPIO_LED1_PIN 5
#define GPIO_LED1_MODE GPIO_Mode_AF
#define GPIO_LED1_AF 1
#define GPIO_LED1_TIMER timer2
#define GPIO_LED1_TIM_CH TIM_Channel_1
#define USE_TIM_2
#define USE_TIM_1
#define CAPTURE_TIMER timer1
#define GPIO_CAPTURE_PORT GPIOC
#define GPIO_CAPTURE_PIN 0
#define GPIO_CAPTURE_TIM_CH_RISING TIM_Channel_1
#define GPIO_CAPTURE_TIM_CH_FALLING TIM_Channel_2
#define GPIO_CAPTURE_AF 2
