#define GPIO_LED1_PORT GPIOC
#define GPIO_LED1_PIN 13
#define GPIO_LED1_AF 1
#define USE_TIM_1
#define STDOUT_USART uart1
#define USE_USART_1
#define GPIO_USART1_TX_PORT GPIOA
#define GPIO_USART1_TX_PIN 9
#define GPIO_USART1_TX_AF 1
#define GPIO_USART1_RX_PORT GPIOA
#define GPIO_USART1_RX_PIN 10
#define GPIO_USART1_RX_AF 1
#define GPIO_USART2_TX_PORT GPIOA
#define GPIO_USART2_TX_PIN 2
#define GPIO_USART2_TX_AF 1
#define GPIO_USART2_RX_PORT GPIOA
#define GPIO_USART2_RX_PIN 3
#define GPIO_USART2_RX_AF 1
#define ADC_CHAN 1
