
TARGET_MCU = STM32F350G8
STARTUP_FILE = stm32f350

BOARD_DEFINES += \
 -DGPIO_LED1_PORT=GPIOC \
 -DGPIO_LED1_PIN=13 \
 -DGPIO_LED1_AF=1 \
 -DUSE_TIM_1
 -DSTDOUT_USART=uart1 \
 -DUSE_USART_1 \
 -DGPIO_USART1_TX_PORT=GPIOA \
 -DGPIO_USART1_TX_PIN=9 \
 -DGPIO_USART1_TX_AF=1 \
 -DGPIO_USART1_RX_PORT=GPIOA \
 -DGPIO_USART1_RX_PIN=10 \
 -DGPIO_USART1_RX_AF=1 \
 -DGPIO_USART2_TX_PORT=GPIOA \
 -DGPIO_USART2_TX_PIN=2 \
 -DGPIO_USART2_TX_AF=1 \
 -DGPIO_USART2_RX_PORT=GPIOA \
 -DGPIO_USART2_RX_PIN=3 \
 -DGPIO_USART2_RX_AF=1 \
 