
TARGET_MCU = STM32F303RE

BOARD_DEFINES += \
 -DGPIO_USART1_TX_PORT=GPIOA \
 -DGPIO_USART1_TX_PIN=9 \
 -DGPIO_USART1_TX_MODE=GPIO_Mode_AF \
 -DGPIO_USART1_TX_AF=1 \
 -DGPIO_USART1_RX_PORT=GPIOA \
 -DGPIO_USART1_RX_PIN=10 \
 -DGPIO_USART1_RX_MODE=GPIO_Mode_AF \
 -DGPIO_USART1_RX_AF=1 \
 -DGPIO_LED1_PORT=GPIOC \
 -DGPIO_LED1_PIN=9 \
 -DGPIO_LED1_MODE=GPIO_Mode_OUT \
 -DGPIO_LED1_AF=0
