TARGET_MCU = STM32F103RC

BOARD_DEFINES +=
#define USE_USART_1
#define GPIO_USART1_TX_PORT=GPIOA
#define GPIO_USART1_TX_PIN=9
#define GPIO_USART1_TX_MODE=GPIO_Mode_AF_PP
#define GPIO_USART1_REMAP=1
#define GPIO_USART1_RX_PORT=GPIOA
#define GPIO_USART1_RX_PIN=10
#define GPIO_USART1_RX_MODE=GPIO_Mode_AF_PP
#define USE_USART_3
#define GPIO_USART3_TX_PORT=GPIOA
#define GPIO_USART3_TX_PIN=9
#define GPIO_USART3_TX_MODE=GPIO_Mode_AF_PP
#define GPIO_USART3_REMAP=1
#define GPIO_USART3_RX_PORT=GPIOA
#define GPIO_USART3_RX_PIN=10
#define GPIO_USART3_RX_MODE=GPIO_Mode_AF_PP
#define GPIO_LED1_PORT=GPIOC
#define GPIO_LED1_PIN=13
#define GPIO_LED1_MODE=GPIO_Mode_Out_PP
#define GPIO_LED1_TIMER=timer1
#define GPIO_LED1_TIM_CH=TIM_Channel_1
#define GPIO_LED1_REMAP=0
